from app.schemas import TerminalProfile, TransactionRequest


TERMINALS: dict[str, TerminalProfile] = {
    "POS-MUM-001": TerminalProfile(
        terminal_id="POS-MUM-001",
        location="Mumbai branch partner POS",
        expected_frequency_ghz=2.45,
        expected_rssi_dbm=-42.0,
        expected_path_loss_db=44.0,
        max_s11_db=-15.0,
        status="active",
    ),
    "POS-BLR-002": TerminalProfile(
        terminal_id="POS-BLR-002",
        location="Bengaluru airport retail POS",
        expected_frequency_ghz=2.45,
        expected_rssi_dbm=-48.0,
        expected_path_loss_db=50.0,
        max_s11_db=-15.0,
        status="active",
    ),
}


DEMO_CASES: list[TransactionRequest] = [
    TransactionRequest(
        transaction_id="case-a-legitimate",
        customer_id="cust-1042",
        amount=1299.0,
        merchant="FreshMart",
        merchant_category="grocery",
        country="IN",
        location="Mumbai, IN",
        timestamp="2026-09-14T10:30:00Z",
        hour_of_day=18,
        transactions_last_hour=1,
        distance_from_home_km=4.2,
        terminal={
            "terminal_id": "POS-MUM-001",
            "rssi_dbm": -41.2,
            "s11_db": -18.7,
            "frequency_ghz": 2.45,
            "path_loss_db": 43.5,
        },
    ),
    TransactionRequest(
        transaction_id="case-b-travel-shift",
        customer_id="cust-1042",
        amount=8400.0,
        merchant="SkyRoute Travel",
        merchant_category="travel",
        country="IN",
        location="Bengaluru, IN",
        timestamp="2026-09-14T23:45:00Z",
        hour_of_day=5,
        transactions_last_hour=2,
        distance_from_home_km=980.0,
        previous_transaction_id="case-a-legitimate",
        terminal={
            "terminal_id": "POS-BLR-002",
            "rssi_dbm": -49.1,
            "s11_db": -16.4,
            "frequency_ghz": 2.45,
            "path_loss_db": 51.2,
        },
    ),
    TransactionRequest(
        transaction_id="case-c-credential-attack",
        customer_id="cust-1042",
        amount=74500.0,
        merchant="Nova Electronics",
        merchant_category="electronics",
        country="US",
        location="New York, US",
        timestamp="2026-09-14T20:35:00Z",
        hour_of_day=2,
        transactions_last_hour=8,
        distance_from_home_km=13500.0,
        previous_transaction_id="case-b-travel-shift",
        terminal={
            "terminal_id": "ROGUE-404",
            "rssi_dbm": -71.0,
            "s11_db": -8.2,
            "frequency_ghz": 2.39,
            "path_loss_db": 78.0,
        },
    ),
    TransactionRequest(
        transaction_id="case-d-stolen-card-legit-terminal",
        customer_id="cust-1042",
        amount=52000.0,
        merchant="Luxury Vault",
        merchant_category="electronics",
        country="IN",
        location="Mumbai, IN",
        timestamp="2026-09-14T21:10:00Z",
        hour_of_day=23,
        transactions_last_hour=5,
        distance_from_home_km=7.0,
        previous_transaction_id="case-c-credential-attack",
        terminal={
            "terminal_id": "POS-MUM-001",
            "rssi_dbm": -42.7,
            "s11_db": -17.9,
            "frequency_ghz": 2.45,
            "path_loss_db": 44.8,
        },
    ),
]
